kind: BuildConfig
apiVersion: v1
metadata:
  name: java-backend
spec:
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk:11-slim'
  output:
    to:
      kind: ImageStreamTag
      name: openshift-testapp-java:latest
