apiVersion: v1
kind: Template
parameters:
  - name: DOCKER_TAG
    required: true

objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: java-backend
    spec:
      output:
        to:
          kind: DockerImage
          name: ghcr.io/fabiankuhn/java-backend:${DOCKER_TAG}
        pushSecret:
          name: docker-hub-secret
      strategy:
        dockerStrategy:
          dockerfilePath: backend/Dockerfile
        type: Docker
      successfulBuildsHistoryLimit: 5
