kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "java-backend"
  labels:
    app: "java-backend"
spec:
  template:
    metadata:
      labels:
        name: "java-backend"
    spec:
      containers:
        - name: "java-backend"
          image: "ghcr.io/fabiankuhn/java-backend:latest"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 2
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
