apiVersion: v1
kind: Service
metadata:
  name: java-backend
  labels:
    app: My-Awesome-Apps
spec:
  selector:
    deploymentconfig: java-backend
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
